package API.Rest.de.la.aplicacion.Voll.med.medico;

import API.Rest.de.la.aplicacion.Voll.med.direccion.DatosDireccion;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Pattern;

public record DatosRegistroMedico(
                                  @NotBlank String nombre,
                                  @NotBlank @Email String email,
                                  @NotBlank String telefono,
                                  @NotBlank @Pattern(regexp = "\\d{7,9}") String documento,
                                  @NotNull Especialidad especialidad,
                                  @NotNull @Valid DatosDireccion direccion) {

    // Constructor is automatically generated by the record
    // No need to explicitly define it unless you want to add validation or transformation logic) {
}
